In [29]:
import pandas as pd
from os import listdir
from os.path import isfile, join
from datetime import datetime

In [71]:
path = "data/csse_covid_19_daily_reports_us"
l = []

files = [f for f in listdir(path) if (isfile(join(path, f)) and f.endswith('.csv'))]
for f in files:
    filename = join(path, f)
    df = pd.read_csv(filename)
    df['Date'] = (datetime.strptime(f[0:10], "%m-%d-%Y")).strftime("%Y-%m-%d")
    df = df.dropna(how='all')
    l.append(df)

In [72]:
data = pd.concat(l)
data = data[data['Province_State'] != 'Diamond Princess']
data = data[data['Province_State'] != 'Grand Princess']
data = data[data['Province_State'] != 'American Samoa']
data = data[data['Province_State'] != 'Guam']
data = data[data['Province_State'] != 'Northern Mariana Islands']
data = data[data['Province_State'] != 'Puerto Rico']
data = data[data['Province_State'] != 'Virgin Islands']
data = data[data['Province_State'] != 'Recovered']

In [73]:
data

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,Date,People_Tested,Mortality_Rate
0,Alabama,US,2021-01-02 05:30:44,32.3182,-86.9023,365747,4872,202137.0,158738.0,1.0,...,1885216.0,NaN,1.332068,84000001.0,USA,38448.804196,NaN,2021-01-01,NaN,NaN
1,Alaska,US,2021-01-02 05:30:44,61.3707,-152.4044,46986,206,7165.0,39615.0,2.0,...,1275750.0,NaN,0.438428,84000002.0,USA,174391.185778,NaN,2021-01-01,NaN,NaN
3,Arizona,US,2021-01-02 05:30:44,33.7298,-111.4312,530267,9015,76934.0,444318.0,4.0,...,2878868.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN,2021-01-01,NaN,NaN
4,Arkansas,US,2021-01-02 05:30:44,34.9697,-92.3731,229442,3711,199247.0,26484.0,5.0,...,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN,2021-01-01,NaN,NaN
5,California,US,2021-01-02 05:30:44,36.1162,-119.6816,2365024,26363,NaN,2309915.0,6.0,...,33058311.0,NaN,1.125160,84000006.0,USA,83666.036710,NaN,2021-01-01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Virginia,US,2021-01-01 05:30:27,37.7693,-78.1700,349584,5032,30707.0,313845.0,51.0,...,4255991.0,NaN,1.439425,84000051.0,USA,49862.123205,NaN,2020-12-31,NaN,NaN
54,Washington,US,2021-01-01 05:30:27,47.4009,-121.4905,246752,3461,NaN,243291.0,53.0,...,3805390.0,NaN,1.402623,84000053.0,USA,49972.993711,NaN,2020-12-31,NaN,NaN
55,West Virginia,US,2021-01-01 05:30:27,38.4912,-80.9545,85334,1338,59508.0,24488.0,54.0,...,1514520.0,NaN,1.567957,84000054.0,USA,84508.692646,NaN,2020-12-31,NaN,NaN
56,Wisconsin,US,2021-01-01 05:30:27,44.2685,-89.6165,520438,5242,447500.0,67696.0,55.0,...,5348488.0,NaN,1.007229,84000055.0,USA,91860.002192,NaN,2020-12-31,NaN,NaN
57,Wyoming,US,2021-01-01 05:30:27,42.7560,-107.3025,44409,438,42570.0,1401.0,56.0,...,501784.0,NaN,0.986287,84000056.0,USA,86699.990842,NaN,2020-12-31,NaN,NaN

In [74]:
pd.unique(data.Province_State)

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [76]:
len(pd.unique(data.Province_State))

51

In [82]:
data.to_csv('data/covid_data_us.csv', index=False)

In [83]:
data

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,...,Total_Test_Results,People_Hospitalized,Case_Fatality_Ratio,UID,ISO3,Testing_Rate,Hospitalization_Rate,Date,People_Tested,Mortality_Rate
0,Alabama,US,2021-01-02 05:30:44,32.3182,-86.9023,365747,4872,202137.0,158738.0,1.0,...,1885216.0,NaN,1.332068,84000001.0,USA,38448.804196,NaN,2021-01-01,NaN,NaN
1,Alaska,US,2021-01-02 05:30:44,61.3707,-152.4044,46986,206,7165.0,39615.0,2.0,...,1275750.0,NaN,0.438428,84000002.0,USA,174391.185778,NaN,2021-01-01,NaN,NaN
3,Arizona,US,2021-01-02 05:30:44,33.7298,-111.4312,530267,9015,76934.0,444318.0,4.0,...,2878868.0,NaN,1.700087,84000004.0,USA,39551.860582,NaN,2021-01-01,NaN,NaN
4,Arkansas,US,2021-01-02 05:30:44,34.9697,-92.3731,229442,3711,199247.0,26484.0,5.0,...,2051488.0,NaN,1.617402,84000005.0,USA,67979.497674,NaN,2021-01-01,NaN,NaN
5,California,US,2021-01-02 05:30:44,36.1162,-119.6816,2365024,26363,NaN,2309915.0,6.0,...,33058311.0,NaN,1.125160,84000006.0,USA,83666.036710,NaN,2021-01-01,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53,Virginia,US,2021-01-01 05:30:27,37.7693,-78.1700,349584,5032,30707.0,313845.0,51.0,...,4255991.0,NaN,1.439425,84000051.0,USA,49862.123205,NaN,2020-12-31,NaN,NaN
54,Washington,US,2021-01-01 05:30:27,47.4009,-121.4905,246752,3461,NaN,243291.0,53.0,...,3805390.0,NaN,1.402623,84000053.0,USA,49972.993711,NaN,2020-12-31,NaN,NaN
55,West Virginia,US,2021-01-01 05:30:27,38.4912,-80.9545,85334,1338,59508.0,24488.0,54.0,...,1514520.0,NaN,1.567957,84000054.0,USA,84508.692646,NaN,2020-12-31,NaN,NaN
56,Wisconsin,US,2021-01-01 05:30:27,44.2685,-89.6165,520438,5242,447500.0,67696.0,55.0,...,5348488.0,NaN,1.007229,84000055.0,USA,91860.002192,NaN,2020-12-31,NaN,NaN
57,Wyoming,US,2021-01-01 05:30:27,42.7560,-107.3025,44409,438,42570.0,1401.0,56.0,...,501784.0,NaN,0.986287,84000056.0,USA,86699.990842,NaN,2020-12-31,NaN,NaN